In [11]:
import pandas as pd
import numpy as np
import time

In [2]:
r=pd.read_csv("Ciudades_Visitadas_Latinoamerica_2023.csv")
r.head(2)

Ciudad       País  Población  Visitantes
0  Ciudad de México     México    9265833    21000000
1      Buenos Aires  Argentina    3059574    15000000

In [4]:
np.round(r['Población'].mean())

5863277.0

In [5]:
np.min(r['Visitantes'])

3000000

In [6]:
np.max(r['Visitantes'])

21000000

In [7]:
mi_array= np.array([1,2,3,4,5])
mi_array

array([1, 2, 3, 4, 5])

In [8]:
lista_grande = list(range(1000000)) # una lista de 1 millon de elementos
array_grande = np.array(lista_grande) # un array con 1 millon de elementos

In [12]:
#para crear una marca de tiempo
inicio_lista = time.time()
for i in lista_grande:
    i ** 2
fin_lista= time.time()
print("tiempo lista :",fin_lista - inicio_lista)

tiempo lista : 0.2859976291656494


In [14]:
inicio_array = time.time()
array_grande ** 2
fin_array =time.time()
print("tiempo array : ", fin_array -inicio_array)

tiempo array :  0.01700115203857422


In [16]:
array = np.array([1,2,3]) # una sola dimension 
len(array)

3

In [30]:
array_2d= np.array([[1,2,3],[4,5,6],[7,8,9]])
array_2d  #array bidemensionales

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
len(array_2d)

2

In [23]:
#concatenar array
x=[1,2,3]
y=[4,5,6]
z=[7,8,9]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a=[[1,2],[3,4]]
b=[[5,6],[7,8]]
np.concatenate([a,b], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [28]:
a=[[1,2],[3,4]]
b=[[5,6],[7,8]]
np.concatenate([a,b], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [29]:
array_con=np.concatenate([a,b], axis=0)
array_con.shape

(4, 2)

In [34]:
#indexaciones 
array[0]

1

In [32]:
array_2d[0] #obtengo la fila 

array([1, 2, 3])

In [33]:
array_2d[1][2]

6

In [35]:
#slicing 
array[1:4]

array([2, 3])

In [36]:
array_2d[1,:] #fila completa 

array([4, 5, 6])

In [37]:
array_2d[1, 1:3]

array([5, 6])

In [38]:
array_2d[:, 1] # todo pero de el primero

array([2, 5, 8])

In [40]:
#modicamos la forma del array
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a_mod = a.reshape(3,3)
a_mod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a_trasnpuesto = a_mod.transpose()
a_trasnpuesto # trasnspuesto

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [45]:
# flatten achatado 
a_fla = a_mod.flatten()
a_fla

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
#operaciones con los array suma , resta etc 
c=np.array([1,2,3])
d=np.array([[0],[10],[20],[30]])
suma= c + d
suma

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [53]:
a = np.array ([1,2,3])
b = np.array ([4,5,6])
re = np.add( a,b)
re

array([5, 7, 9])

In [54]:
re = np.exp(a) #exponencial
re

array([ 2.71828183,  7.3890561 , 20.08553692])

In [56]:
re = np.log(a) #logaritmo
re

array([0.        , 0.69314718, 1.09861229])

In [57]:
re = np.sqrt(a)#para hacer una raiz cuadrada
re

array([1.        , 1.41421356, 1.73205081])

In [58]:
#limpieza de datos 
#como tratar los datos faltantes 
# se representan como np.nan (np not a number)
ay = np.array([1,2,np.nan, 4,5])
ay

array([ 1.,  2., nan,  4.,  5.])

In [59]:
#comprobamos si en un array hay un dato nan
np.isnan(ay)

array([False, False,  True, False, False])

In [61]:
np.nanmean(ay)# promedio aunque tenga numeros no validos nan

3.0

In [63]:
#reemplaza el valor faltante con cero
ay_con_cero = np.where(np.isnan(ay),0,ay)
ay_con_cero

array([1., 2., 0., 4., 5.])

In [66]:
#reemplaza el valor faltante por el promedio
promedio = np.nanmean(ay)
promedio_a = np.where(np.isnan(ay), promedio, ay)
promedio_a

array([1., 2., 3., 4., 5.])

In [68]:
#eliminamos el valor faltante 
e=ay[~np.isnan(ay)]
print(e)

[1. 2. 4. 5.]


In [69]:
path = pd.read_csv("datos_meteorologicos.csv")
path.head(2)

Fecha  Temperatura  Precipitación    Humedad
0  01/01/2010    17.440675      10.957482  52.384637
1  02/01/2010    25.759468       5.315628  30.633530

In [71]:
print(path.shape)

(5110, 4)


In [72]:
print(path.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Fecha          5110 non-null   object 
 1   Temperatura    4855 non-null   float64
 2   Precipitación  4855 non-null   float64
 3   Humedad        4855 non-null   float64
dtypes: float64(3), object(1)
memory usage: 159.8+ KB
None


In [73]:
print(path.describe())

       Temperatura  Precipitación      Humedad
count  4855.000000    4855.000000  4855.000000
mean     14.889296       9.901604    54.359061
std      14.440466       5.801842    26.096345
min      -9.996378       0.003008    10.014980
25%       2.651777       4.756907    31.866578
50%      14.693274       9.853698    54.254478
75%      27.381451      14.966997    77.029500
max      39.998201      19.999559    99.996582


In [76]:
# convertir las columnas del Dataframe en arrays de Numpy 
print(path.head(1))

        Fecha  Temperatura  Precipitación    Humedad
0  01/01/2010    17.440675      10.957482  52.384637


In [77]:
tep = path["Temperatura"].to_numpy()
pre= path["Precipitación"].to_numpy()
hu=path ["Humedad"].to_numpy()

In [82]:
print(tep)

[17.4406752  25.75946832 20.1381688  ... 29.87359717         nan
 37.30804318]


In [83]:
print(pre)

[10.957482    5.31562765 15.31770609 ...  4.61501177         nan
  7.33051023]


In [85]:
print(hu)

[52.38463749 30.63352983 41.49671458 ... 18.36284738         nan
 50.64621058]


In [88]:
#identificar las datos faltantes en los arrays y 
#reemplazarlos por el promedio de los valores 
t_nulo = np.isnan(tep)
p_nulo = np.isnan(pre)
h_nulo = np.isnan(hu)
print(t_nulo)
print(p_nulo)
print(h_nulo)

[False False False ... False  True False]
[False False False ... False  True False]
[False False False ... False  True False]


In [89]:
#identificar el promedio de cada array
t_promedio = np.nanmean(tep)
p_promedio = np.nanmean(pre)
h_promedio = np.nanmean(hu)
#reeemplazar los valores nulos con el promedio del array 
tep[t_nulo]=t_promedio
pre[p_nulo]=p_promedio
hu[h_nulo] =h_promedio
print(tep)

[17.4406752  25.75946832 20.1381688  ... 29.87359717 14.88929572
 37.30804318]


In [96]:
#realizar analisis estadisticos 
#temperatura promedio 
t_promedio=np.nanmean(tep)
print(t_promedio)
print("----------------------------")
#total de precipitaciones
p_total = np.sum(pre)
print(pre)
print("-----------------------------")
#maxima humedad registrada 
h_max = np.max(hu)
print(hu)
print("-----------------------------")
#fecha mas calurosa
#temperatura mas alta 
mas_calor =np.max(tep)
print(tep)
print("-----------------------------")
#registro de la temperatura mas alta 
registro_calor = np.where(tep == mas_calor)[0][0]
print(registro_calor)
print("-----------------------------")
#fecha mas fria 
fecha_fria = path.iloc[np.where(tep == np.min(tep))[0][0]]["Fecha"]
print(fecha_fria)
print("-----------------------------")

14.889295723531713
----------------------------
[10.957482    5.31562765 15.31770609 ...  4.61501177  9.9016036
  7.33051023]
-----------------------------
[52.38463749 30.63352983 41.49671458 ... 18.36284738 54.3590608
 50.64621058]
-----------------------------
[17.4406752  25.75946832 20.1381688  ... 29.87359717 14.88929572
 37.30804318]
-----------------------------
2749
-----------------------------
23/07/2020
-----------------------------
