In [9]:
import pandas as pd 
import numpy as np 
import time
import random
import matplotlib.pyplot as plt
%matplotlib inline 
#permite que le coloquemos ; en vez de show()
import seaborn as sns 
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression , LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.tree import DecisionTreeClassifier, plot_tree, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor
from sklearn.cluster import KMeans
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
from scipy.cluster.hierarchy import dendrogram, linkage

In [2]:
print("Q-learning")
print("tipo de algortimo de aprendizaje por refuerzo")
print("le permite a un agente imaginarioaprender a tomar decisiones optimas")
print("definine la accion y estado y la calidad de los pasos")

Q-learning
tipo de algortimo de aprendizaje por refuerzo
le permite a un agente imaginarioaprender a tomar decisiones optimas
definine la accion y estado y la calidad de los pasos


In [10]:
dimensiones = (5,5)
estado_inicial = (0,0)
estado_objetivo = (4,4)
obstaculos = [(1,1),(1,3),(2,3),(3,0)]
acciones =[(-1,0),(1,0),(0,-1),(0,1)]
num_estados = dimensiones[0]*dimensiones [1]
num_acciones =len(acciones)
Q=np.zeros((num_estados, num_acciones))
def estado_a_indice(estado):
    return estado[0]*dimensiones[1]+estado[1]

#alpha = factor de la tasa de aprendizaje 
#controla cuando se actualiza el factor Q eb cada 
#paso del aprendizaje 
#gamma = factor de descuento la importancia de las 
#recompensas a futuro 
#epsilon = el agente no repita las mismas decisiones 
#episodios = nos dice el nro de veces que se repite 
alpha = 0.1 
gamma = 0.99
epsilon = 0.2
episodios = 100

def elegir_accion (estado):
    if random.uniform(0,1)< epsilon:
        return random.choice(range(num_acciones))
    else:
        return np.argmax(Q[estado_a_indice(estado)])

def aplicar_accion(estado, accion_idx):
    accion =acciones[accion_idx]
    nuevo_estado = tuple(np.add(estado,accion)%dimensiones)
    if nuevo_estado in obstaculos or nuevo_estado == estado:
        return estado, -100, False
    if nuevo_estado == estado_objetivo:
        return nuevo_estado, 100, True
    return nuevo_estado, -1, False

In [11]:
for episodio in range(episodios):
    estado = estado_inicial
    terminado =False
    while not terminado:
        idx_estado = estado_a_indice(estado)
        accion_idx=elegir_accion(estado)
        nuevo_estado,recompensa, terminado = aplicar_accion(estado,accion_idx)
        idx_nuevo_estado = estado_a_indice(nuevo_estado)
        Q[idx_estado, accion_idx]= Q[idx_estado,accion_idx]+alpha+(recompensa+gamma*np.max(Q[idx_nuevo_estado])-Q[idx_estado,accion_idx])
        estado = nuevo_estado

In [17]:
politica = np.zeros(dimensiones,dtype=int)
for i in range(dimensiones[0]):
    for j in range(dimensiones[1]):
        estado = (i,j)
        idx_estado = estado_a_indice(estado)
        mejor_accion = np.argmax(Q[idx_estado])
        politica[i,j]=mejor_accion
print("politica apredida: (0 es arriba, 1 es abajo, 2 es izquierda, 3 es derecha")
print(politica)
#nos da una matriz donde cada nunero es la mejor posicion a tomar 
#en esa ubicacion 

politica apredida: (0 es arriba, 1 es abajo, 2 es izquierda, 3 es derecha
[[0 0 3 3 0]
 [0 0 0 0 2]
 [0 1 0 0 0]
 [0 0 2 3 1]
 [2 2 3 2 0]]
