In [2]:
print("componentes de sklearn")
print("estimadores ")
print("transformadores")
print("pedictores")

componentes de sklearn
estimadores 
transformadores
pedictores


In [25]:
import pandas as pd 
import numpy as np 
import uuid
import hashlib
import time
import random
import matplotlib.pyplot as plt
%matplotlib inline 
#permite que le coloquemos ; en vez de show()
import seaborn as sns 
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression , LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler, OneHotEncoder
from sklearn.tree import DecisionTreeClassifier, plot_tree, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor
from sklearn.cluster import KMeans
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.utils import resample

In [10]:
#print("cargamos el dataset")
data = load_iris()
X=data.data
y=data.target
#print("dividimos en entrenamiento y prueba")
X_entrena, X_prueba,y_entrena, y_prueba = train_test_split(X,y,
                                                           test_size=0.25,
                                                           random_state=0)
#print("creamos la instancia escalador")
scaler = StandardScaler()
#print("estimador, aprendemos los parametros de fit")
scaler.fit(X_entrena)
#print("transformador,aplicamos la transformacion a los datos")
X_entrena_escalado=scaler.transform(X_entrena)
X_prueba_escalado =scaler.transform(X_prueba)
#print("creamos la instancia modelo")
modelo = LogisticRegression()
#print("estimador, entrenamos el modelo")
modelo.fit(X_entrena_escalado, y_entrena)
#print("predictor, hacemos predicciones y evaluamos el modelo")
y_pred=modelo.predict(X_prueba_escalado)
puntaje = modelo.score(X_prueba_escalado, y_prueba)
print(f"las predicciones son: {y_pred}")
print(f"la precision del modelo es: {puntaje:.2f}")

las predicciones son: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
la precision del modelo es: 0.97


In [14]:
d=np.array([[1,-1,2],[2,0,0],[0,1,-1]])
scaler=MinMaxScaler(feature_range=(0,1))
d_escalada = scaler.fit_transform(d)
d_escalada

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [17]:
i = load_iris()
X=i.data
scaler =MinMaxScaler(feature_range=(0,1))
X_escalado = scaler.fit_transform(X)
print(X[:3]) #datos originales
print(X_escalado[:3]) #transformada entre 0 y 1

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]
[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]]


In [19]:
print("StandarScaler")
#para que tenga un array de media de cero y una desviacion estandar 
# de 1 para algortimos que asumen que tiene una distribucion normal

StandarScaler


In [22]:
scaler2 = StandardScaler()
d_escalada2=scaler2.fit_transform(d)
d_escalada2

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [23]:
np.std(d_escalada2)

1.0

In [30]:
#solo se usa para var categoricas en numeros binarios 
print("One hot Encoder")

One hot Encoder


In [29]:
categorias = np.array([["rojo"],["verde"],["azul"],["verde"],["verde"],["azul"]])
encoder = OneHotEncoder(sparse_output=False)#evitamos una matrix dispersa 
data_codificada = encoder.fit_transform(categorias)
data_codificada

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [36]:
from sklearn.feature_selection import SelectKBest, SelectFromModel, chi2
a = load_iris()
X=data.data
y=data.target
X_train, X_test, y_train, y_test=train_test_split(X, y,test_size=0.2, random_state=42)
print("tamaño del conjunto total", len(X))
print("tamaño del conjunto de train", len(X_train))
print("tamaño del conjunto de pruebas", len(X_test))
selector =SelectKBest(chi2, k=2)#quiero saber las 2 caracteristicas mas importantes
X_nuevo=selector.fit_transform(X_train, y_train)
m = RandomForestClassifier(n_estimators=100, random_state=42)
selector2 = SelectFromModel(m)
X_importante =selector2.fit_transform(X_train, y_train)

tamaño del conjunto total 150
tamaño del conjunto de train 120
tamaño del conjunto de pruebas 30
